#! /bin/csh -f
#
#Clean course database
#
echo " "
echo " *** Course Database Cleaning Tool ***"
echo " "
echo " Removes all *.cd-, *.cd%, *.cdslck files\!"
echo " Removes the simulation directory and its contents\!"
echo " Removes files and directories created during lab exercises"
echo " "
echo -n "    Begin cleaning `pwd` course database? [y]/n >"
set ans = $<
#
if ( "$ans" == "" || "$ans" == "y" ) then
	echo " "
	echo " Size in Kbytes before cleaning is: `du -sk`"
	echo " "
	echo -n " Cleaning ..."
else
	echo " "
	echo "Exiting."
	echo " "
	exit
endif
#
foreach file ( `find . | grep \\.cd-$` )
rm -f $file
end

foreach file ( `find . | grep \\.cd%$` )
rm -f $file
end
#
foreach file ( `find . | grep \\.cdslck$` )
rm -f $file
end
foreach file ( `find . | grep \\.log$` )
rm -f $file
end
#foreach file ( `find . | grep \\.txt$` )
#rm -f $file
#end
foreach file ( `find . | grep \\.save$` )
rm -f $file
end
rm -rf ExactSelected.png
rm -rf ExactAllSingle.png
rm -rf ResizeAll.png
rm -rf print.pdf
rm -rf *.png
rm -rf print.pdf
rm -rf ./myLib
rm -rf ./simulation
rm -rf .cadence	
rm -rf ./.artist_states/training/ampTest/spectre/lab4-1
rm -rf *.csv
rm -rf ./parametric
rm -rf ./training/InlineAmpTest/config
rm -rf *.ocn listDevices.il myOut cdsSession.save tempfile ./.tmp_* logs_*
rm -rf ./training/peakTestv/maestro
rm -rf ./training/ampTest/maestro
rm -rf ./perf_logs
cp -rf ./training/ampTest/.maestro_orig ./training/ampTest/maestro
rm -rf ./*.log
#
#foreach file ( `find . | grep \\.test$` )
#rm -rf $file
#end
#
echo " Done."
echo " "
echo " Size in Kbytes after cleaning is: `du -sk`"
echo " "
#
