/** 3155835710 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef PLL_250MHZ_MDIV_INST_STATIC_H
#define PLL_250MHZ_MDIV_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_CLKFB_448	(*((double *) &instData [448]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_CLKFB_440	(*((double *) &instData [440]))	/* Branch Reln : Size = 8 bytes. */
#define _CLKFB_flow_424	(*((long *) &instData [424]))	/* Hidden Node : Size = 4 bytes. */
#define _I_Dynamic_CLKVCO_global_VSS_416	(*((double *) &instData [416]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_CLKVCO_global_VSS_408	(*((double *) &instData [408]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_di_CLKFB_400	(*((double *) &instData [400]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_global_VDD_384	(*((double *) &instData [384]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_global_VDD_336	(*((double *) &instData [336]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_CLKVCO_global_VSS_320	(*((double *) &instData [320]))	/* Branch Load Group : Size = 8 bytes. */
#define _thr_280	(*((double *) &instData [280]))	/* VT_REAL : Size = 8 bytes. */
#define _global_VDD_value_240	(*((double *) &instData [240]))	/* VT_REAL : Size = 8 bytes. */
#define _global_VSS_value_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _CLKVCO_dir_188	(*((long *) &instData [188]))	/* VT_INT : Size = 4 bytes. */
#define _count_CLKFB_176	(*((long *) &instData [176]))	/* VT_INT : Size = 4 bytes. */
#define _fun_CLKFB_164	(*((long *) &instData [164]))	/* VT_INT : Size = 4 bytes. */
#define _CLKFB_t2_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _CLKFB_t1_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _CLKFB_delay_48	(*((double *) &instData [48]))	/* VT_REAL : Size = 8 bytes. */
#define _global_VDD_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _global_VSS_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _CLKVCO_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _CLKFB_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* PLL_250MHZ_MDIV_INST_STATIC_H */
