/** 657267681 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef PLL_VCO_250MHZ_INST_STATIC_H
#define PLL_VCO_250MHZ_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_VCO_CLK_PH_1__2080	(*((double *) &instData [2080]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_1__2072	(*((double *) &instData [2072]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_1__flow_2056	(*((long *) &instData [2056]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_2__2048	(*((double *) &instData [2048]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_2__2040	(*((double *) &instData [2040]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_2__flow_2024	(*((long *) &instData [2024]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_3__2016	(*((double *) &instData [2016]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_3__2008	(*((double *) &instData [2008]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_3__flow_1992	(*((long *) &instData [1992]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_4__1984	(*((double *) &instData [1984]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_4__1976	(*((double *) &instData [1976]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_4__flow_1960	(*((long *) &instData [1960]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_5__1952	(*((double *) &instData [1952]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_5__1944	(*((double *) &instData [1944]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_5__flow_1928	(*((long *) &instData [1928]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_6__1920	(*((double *) &instData [1920]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_6__1912	(*((double *) &instData [1912]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_6__flow_1896	(*((long *) &instData [1896]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_7__1888	(*((double *) &instData [1888]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_7__1880	(*((double *) &instData [1880]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_7__flow_1864	(*((long *) &instData [1864]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_8__1856	(*((double *) &instData [1856]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_8__1848	(*((double *) &instData [1848]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_8__flow_1832	(*((long *) &instData [1832]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_9__1824	(*((double *) &instData [1824]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_9__1816	(*((double *) &instData [1816]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_9__flow_1800	(*((long *) &instData [1800]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_10__1792	(*((double *) &instData [1792]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_10__1784	(*((double *) &instData [1784]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_10__flow_1768	(*((long *) &instData [1768]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_VCO_CLK_PH_0__1760	(*((double *) &instData [1760]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_VCO_CLK_PH_0__1752	(*((double *) &instData [1752]))	/* Branch Reln : Size = 8 bytes. */
#define _VCO_CLK_PH_0__flow_1736	(*((long *) &instData [1736]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_IEXT_100u_1728	(*((double *) &instData [1728]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_IEXT_100u_1720	(*((double *) &instData [1720]))	/* Branch Reln : Size = 8 bytes. */
#define _IEXT_100u_flow_1704	(*((long *) &instData [1704]))	/* Hidden Node : Size = 4 bytes. */
#define _I_Dynamic_PD_VSS_1696	(*((double *) &instData [1696]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_PD_VSS_1688	(*((double *) &instData [1688]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_Vcontrol_VSS_1680	(*((double *) &instData [1680]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_Vcontrol_VSS_1672	(*((double *) &instData [1672]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1664	(*((double *) &instData [1664]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1648	(*((double *) &instData [1648]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1624	(*((double *) &instData [1624]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1608	(*((double *) &instData [1608]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1584	(*((double *) &instData [1584]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1568	(*((double *) &instData [1568]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1544	(*((double *) &instData [1544]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1528	(*((double *) &instData [1528]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1504	(*((double *) &instData [1504]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1488	(*((double *) &instData [1488]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1464	(*((double *) &instData [1464]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1448	(*((double *) &instData [1448]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1424	(*((double *) &instData [1424]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1408	(*((double *) &instData [1408]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1384	(*((double *) &instData [1384]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1368	(*((double *) &instData [1368]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1344	(*((double *) &instData [1344]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1328	(*((double *) &instData [1328]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1304	(*((double *) &instData [1304]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1288	(*((double *) &instData [1288]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_Vcontrol_1264	(*((double *) &instData [1264]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1248	(*((double *) &instData [1248]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1224	(*((double *) &instData [1224]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_1104	(*((double *) &instData [1104]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_PD_VSS_1088	(*((double *) &instData [1088]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_1072	(*((double *) &instData [1072]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_Vcontrol_VSS_1056	(*((double *) &instData [1056]))	/* Branch Load Group : Size = 8 bytes. */
#define _thr_1016	(*((double *) &instData [1016]))	/* VT_REAL : Size = 8 bytes. */
#define _VDD_value_976	(*((double *) &instData [976]))	/* VT_REAL : Size = 8 bytes. */
#define _VSS_value_936	(*((double *) &instData [936]))	/* VT_REAL : Size = 8 bytes. */
#define _run_920	(*((long *) &instData [920]))	/* VT_INT : Size = 4 bytes. */
#define _fun_908	(*((long *) &instData [908]))	/* VT_INT : Size = 4 bytes. */
#define _VCO_CLK_PH_1_delay_872	(*((double *) &instData [872]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_2_delay_832	(*((double *) &instData [832]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_3_delay_792	(*((double *) &instData [792]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_4_delay_752	(*((double *) &instData [752]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_5_delay_712	(*((double *) &instData [712]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_6_delay_672	(*((double *) &instData [672]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_7_delay_632	(*((double *) &instData [632]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_8_delay_592	(*((double *) &instData [592]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_9_delay_552	(*((double *) &instData [552]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_10_delay_512	(*((double *) &instData [512]))	/* VT_REAL : Size = 8 bytes. */
#define _PD_thr_472	(*((double *) &instData [472]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_0_fall_432	(*((double *) &instData [432]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_0_rise_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_0_high_352	(*((double *) &instData [352]))	/* VT_REAL : Size = 8 bytes. */
#define _VCO_CLK_PH_0_low_312	(*((double *) &instData [312]))	/* VT_REAL : Size = 8 bytes. */
#define _width_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _period_232	(*((double *) &instData [232]))	/* VT_REAL : Size = 8 bytes. */
#define _next_fall_192	(*((double *) &instData [192]))	/* VT_REAL : Size = 8 bytes. */
#define _next_rise_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _start_time_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _ttol_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _Vcontrol_96	(*((long *) &instData [96]))	/* VT_NODE : Size = 4 bytes. */
#define _VSS_88	(*((long *) &instData [88]))	/* VT_NODE : Size = 4 bytes. */
#define _VDD_80	(*((long *) &instData [80]))	/* VT_NODE : Size = 4 bytes. */
#define _PD_72	(*((long *) &instData [72]))	/* VT_NODE : Size = 4 bytes. */
#define _IEXT_100u_64	(*((long *) &instData [64]))	/* VT_NODE : Size = 4 bytes. */
#define _VCO_CLK_PH_16	(*((long *) &instData [16]))	/* VT_NODE : Size = 4 bytes. */


#endif /* PLL_VCO_250MHZ_INST_STATIC_H */
