/** 183419105 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef AMPV_INST_STATIC_H
#define AMPV_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vref_vout_688	(*((double *) &instData [688]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vref_vout_680	(*((double *) &instData [680]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_vref_cout_672	(*((double *) &instData [672]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vref_cout_664	(*((double *) &instData [664]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_vref_vin_n_656	(*((double *) &instData [656]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vref_vin_n_648	(*((double *) &instData [648]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_vref_vin_p_640	(*((double *) &instData [640]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vref_vin_p_632	(*((double *) &instData [632]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_vin_p_vin_n_624	(*((double *) &instData [624]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vin_p_vin_n_616	(*((double *) &instData [616]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_vout_608	(*((double *) &instData [608]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vref_vout_592	(*((double *) &instData [592]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vref_cout_576	(*((double *) &instData [576]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_vref_cout_560	(*((double *) &instData [560]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vin_p_vin_n_552	(*((double *) &instData [552]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vref_cout_536	(*((double *) &instData [536]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_vin_p_vin_n_520	(*((double *) &instData [520]))	/* Branch Load Group : Size = 8 bytes. */
#define _cout_508	(*((long *) &instData [508]))	/* VT_NODE : Size = 4 bytes. */
#define _vin_val_472	(*((double *) &instData [472]))	/* VT_REAL : Size = 8 bytes. */
#define _vmax_in_432	(*((double *) &instData [432]))	/* VT_REAL : Size = 8 bytes. */
#define _r1_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _gm_nom_352	(*((double *) &instData [352]))	/* VT_REAL : Size = 8 bytes. */
#define _c1_312	(*((double *) &instData [312]))	/* VT_REAL : Size = 8 bytes. */
#define _vspply_n_288	(*((double *) &instData [288]))	/* VT_REAL : Size = 8 bytes. */
#define _vspply_p_264	(*((double *) &instData [264]))	/* VT_REAL : Size = 8 bytes. */
#define _vsoft_240	(*((double *) &instData [240]))	/* VT_REAL : Size = 8 bytes. */
#define _rout_216	(*((double *) &instData [216]))	/* VT_REAL : Size = 8 bytes. */
#define _rsrc_192	(*((double *) &instData [192]))	/* VT_REAL : Size = 8 bytes. */
#define _iin_max_168	(*((double *) &instData [168]))	/* VT_REAL : Size = 8 bytes. */
#define _ibias_144	(*((double *) &instData [144]))	/* VT_REAL : Size = 8 bytes. */
#define _vin_offset_120	(*((double *) &instData [120]))	/* VT_REAL : Size = 8 bytes. */
#define _rin_96	(*((double *) &instData [96]))	/* VT_REAL : Size = 8 bytes. */
#define _freq_unitygain_72	(*((double *) &instData [72]))	/* VT_REAL : Size = 8 bytes. */
#define _gain_48	(*((double *) &instData [48]))	/* VT_REAL : Size = 8 bytes. */
#define _vin_n_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _vin_p_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _vref_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vout_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* AMPV_INST_STATIC_H */
