/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include "ahdlcmi.h"

int ahdlBsourceInterfaceVersion() {
   return 1; /* Only used when version >= spectre's BsourceInterfaceVersion */
}

extern int PLL_PFD_DcFuncDerLoad(int, char*, char*, char**);
extern int PLL_PFD_DcFuncLoad(int, char*, char*, char**);
extern int PLL_PFD_TranFuncDerLoad(int, char*, char*, char**);
extern int PLL_PFD_TranFuncLoad(int, char*, char*, char**);
extern int PLL_PFD_NoiseLoadBiasDep(int, char*, char*, char**);
extern int PLL_PFD_OpPointCalc(int, char*, char*, char**);

int PLL_PFD_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        PLL_PFD_DcFuncDerLoad,  
                        PLL_PFD_DcFuncLoad,     
                        PLL_PFD_TranFuncDerLoad,
                        PLL_PFD_TranFuncLoad,   
                        PLL_PFD_NoiseLoadBiasDep,
                        PLL_PFD_OpPointCalc
                       );
   return 1; /** success **/
}
