/** 3815359999 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef PLL_PFD_INST_STATIC_H
#define PLL_PFD_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_DN_1384	(*((double *) &instData [1384]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_DN_1376	(*((double *) &instData [1376]))	/* Branch Reln : Size = 8 bytes. */
#define _DN_flow_1360	(*((long *) &instData [1360]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_UP_1352	(*((double *) &instData [1352]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_UP_1344	(*((double *) &instData [1344]))	/* Branch Reln : Size = 8 bytes. */
#define _UP_flow_1328	(*((long *) &instData [1328]))	/* Hidden Node : Size = 4 bytes. */
#define _I_Dynamic_PD_VSS_1320	(*((double *) &instData [1320]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_PD_VSS_1312	(*((double *) &instData [1312]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_REFCLK_VSS_1304	(*((double *) &instData [1304]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_REFCLK_VSS_1296	(*((double *) &instData [1296]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_FBCLK_VSS_1288	(*((double *) &instData [1288]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_FBCLK_VSS_1280	(*((double *) &instData [1280]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1272	(*((double *) &instData [1272]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_1248	(*((double *) &instData [1248]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_1128	(*((double *) &instData [1128]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_PD_VSS_1112	(*((double *) &instData [1112]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_1096	(*((double *) &instData [1096]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_REFCLK_VSS_1080	(*((double *) &instData [1080]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_1064	(*((double *) &instData [1064]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_FBCLK_VSS_1048	(*((double *) &instData [1048]))	/* Branch Load Group : Size = 8 bytes. */
#define _thr_1008	(*((double *) &instData [1008]))	/* VT_REAL : Size = 8 bytes. */
#define _VDD_value_968	(*((double *) &instData [968]))	/* VT_REAL : Size = 8 bytes. */
#define _global_VSS_value_928	(*((double *) &instData [928]))	/* VT_REAL : Size = 8 bytes. */
#define _VSS_value_888	(*((double *) &instData [888]))	/* VT_REAL : Size = 8 bytes. */
#define _DN_fun_876	(*((long *) &instData [876]))	/* VT_INT : Size = 4 bytes. */
#define _FBCLK_DN_tran_delay_840	(*((double *) &instData [840]))	/* VT_REAL : Size = 8 bytes. */
#define _REFCLK_DN_tran_delay_800	(*((double *) &instData [800]))	/* VT_REAL : Size = 8 bytes. */
#define _DN_delay_760	(*((double *) &instData [760]))	/* VT_REAL : Size = 8 bytes. */
#define _DN_fall_720	(*((double *) &instData [720]))	/* VT_REAL : Size = 8 bytes. */
#define _DN_rise_680	(*((double *) &instData [680]))	/* VT_REAL : Size = 8 bytes. */
#define _DN_reset_640	(*((double *) &instData [640]))	/* VT_REAL : Size = 8 bytes. */
#define _FBCLK_thr_600	(*((double *) &instData [600]))	/* VT_REAL : Size = 8 bytes. */
#define _REFCLK_thr_560	(*((double *) &instData [560]))	/* VT_REAL : Size = 8 bytes. */
#define _PD_thr_520	(*((double *) &instData [520]))	/* VT_REAL : Size = 8 bytes. */
#define _UP_fun_508	(*((long *) &instData [508]))	/* VT_INT : Size = 4 bytes. */
#define _FBCLK_UP_tran_delay_472	(*((double *) &instData [472]))	/* VT_REAL : Size = 8 bytes. */
#define _REFCLK_UP_tran_delay_432	(*((double *) &instData [432]))	/* VT_REAL : Size = 8 bytes. */
#define _UP_delay_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _UP_fall_352	(*((double *) &instData [352]))	/* VT_REAL : Size = 8 bytes. */
#define _UP_rise_312	(*((double *) &instData [312]))	/* VT_REAL : Size = 8 bytes. */
#define _UP_reset_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _FBCLK_last_232	(*((double *) &instData [232]))	/* VT_REAL : Size = 8 bytes. */
#define _REFCLK_last_192	(*((double *) &instData [192]))	/* VT_REAL : Size = 8 bytes. */
#define _dead_time_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _dead_region_112	(*((double *) &instData [112]))	/* VT_REAL : Size = 8 bytes. */
#define _ttol_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _global_VDD_76	(*((long *) &instData [76]))	/* VT_NODE : Size = 4 bytes. */
#define _global_VSS_68	(*((long *) &instData [68]))	/* VT_NODE : Size = 4 bytes. */
#define _VSS_60	(*((long *) &instData [60]))	/* VT_NODE : Size = 4 bytes. */
#define _VDD_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _PD_44	(*((long *) &instData [44]))	/* VT_NODE : Size = 4 bytes. */
#define _REFCLK_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _FBCLK_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _UP_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _DN_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* PLL_PFD_INST_STATIC_H */
