$courseName = "VAEAS2618"; 
$courseVersion = "IC618";
$softwareVersion = "IC618ISR26";
$releaseDate = "August 1 2022";
$tempDir = "./.test";
$reportFile = "./.test/testReport";
$hostName = "ANY";
$osName = "Linux,SunOS"; 
$osVersion = "ANY"; 
$cpuArch = "ANY";
$machType = "ANY";
$physMem = "ANY";
$totalSwap = "ANY";
$freeDisk = "100";
$licenseFile = "";
%toolExeAndLicenses = ('virtuoso' => 'Virtuoso_ADE_Assembler', 'spectre' => 'Virtuoso_Spectre');
%toolExeAndNumLicenses = ('virtuoso' => '1', 'spectre' => '1');
%toolExeAndVersion = ('virtuoso' => '6.1.8', 'spectre' => '20.1');
%toolExeAndExpr = ('virtuoso' => '-nograph -replay .test/script1.tcl -log .test/logfile1.log', 'spectre' => '.test/spectre.scs =log .test/logfile2.log');
%toolExeAndLogfile = ('virtuoso' => '.test/logfile1.log', 'spectre' => '.test/logfile2.log');
$additionalLogTestString = "";
