/** 2418039655 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef ACOPENDIFF_INST_STATIC_H
#define ACOPENDIFF_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _LastState_Addr_388	(*((long *) &instData [388]))	/* Switch Branch : Size = 4 bytes. */
#define _CurrState_Addr_384	(*((long *) &instData [384]))	/* Switch Branch : Size = 4 bytes. */
#define _Dynamic_BrAddr_376	(*((double *) &instData [376]))	/* Branch Reln : Size = 8 bytes. */
#define _Static_BrAddr_368	(*((double *) &instData [368]))	/* Branch Reln : Size = 8 bytes. */
#define _outn_inref_flow_352	(*((long *) &instData [352]))	/* Hidden Node : Size = 4 bytes. */
#define _LastState_Addr_332	(*((long *) &instData [332]))	/* Switch Branch : Size = 4 bytes. */
#define _CurrState_Addr_328	(*((long *) &instData [328]))	/* Switch Branch : Size = 4 bytes. */
#define _Dynamic_BrAddr_320	(*((double *) &instData [320]))	/* Branch Reln : Size = 8 bytes. */
#define _Static_BrAddr_312	(*((double *) &instData [312]))	/* Branch Reln : Size = 8 bytes. */
#define _outp_inref_flow_296	(*((long *) &instData [296]))	/* Hidden Node : Size = 4 bytes. */
#define _LastState_Addr_276	(*((long *) &instData [276]))	/* Switch Branch : Size = 4 bytes. */
#define _CurrState_Addr_272	(*((long *) &instData [272]))	/* Switch Branch : Size = 4 bytes. */
#define _Dynamic_BrAddr_264	(*((double *) &instData [264]))	/* Branch Reln : Size = 8 bytes. */
#define _Static_BrAddr_256	(*((double *) &instData [256]))	/* Branch Reln : Size = 8 bytes. */
#define _vos_flow_240	(*((long *) &instData [240]))	/* Hidden Node : Size = 4 bytes. */
#define _Static_d_by_dv_inp_inref_232	(*((double *) &instData [232]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_inn_inref_216	(*((double *) &instData [216]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_inp_inref_200	(*((double *) &instData [200]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_inn_inref_184	(*((double *) &instData [184]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_inn_inp_168	(*((double *) &instData [168]))	/* Branch Load Group : Size = 8 bytes. */
#define _vbias_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _vin_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _gain_64	(*((double *) &instData [64]))	/* VT_REAL : Size = 8 bytes. */
#define _vos_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _outn_44	(*((long *) &instData [44]))	/* VT_NODE : Size = 4 bytes. */
#define _outp_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _inref_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _inn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _inp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* ACOPENDIFF_INST_STATIC_H */
