#! /bin/csh -f
#
#Clean course database
#
echo " "
echo " *** Course Database Cleaning Tool ***"
echo " "
echo " Removes all *.cd-, *.cd%, *.cdslck files\!"
echo " Removes the simulation directory and its contents\!"
echo " Removes files and directories created during lab exercises"
echo " "
echo -n "    Begin cleaning `pwd` course database? [y]/n >"
set ans = $<
#
if ( "$ans" == "" || "$ans" == "y" ) then
	echo " "
	echo " Size in Kbytes before cleaning is: `du -sk`"
	echo " "
	echo -n " Cleaning ..."
else
	echo " "
	echo "Exiting."
	echo " "
	exit
endif
#
foreach file ( `find . | grep \\.cd-$` )
rm -f $file
end

foreach file ( `find . | grep \\.cd%$` )
rm -f $file
end
#
foreach file ( `find . | grep \\.cdslck$` )
rm -f $file
end
foreach file ( `find . | grep \\.log$` )
rm -f $file
end
#foreach file ( `find . | grep \\.txt$` )
#rm -f $file
#end
foreach file ( `find . | grep \\.save$` )
rm -f $file
end
rm -rf .cadence
rm -rf ./simulation
rm -rf ./logs_*
rm -rf ./.tmp_*
rm -rf ./*.csv
rm -rf ./design/multest_devchk/adc_cascode_opamp_sim/maestro
rm -rf ./design/ether_sims/adc_sample_hold_sim/maestro
cp -rf ./design/ether_sims/adc_sample_hold_sim/maestro_orig ./design/ether_sims/adc_sample_hold_sim/maestro
rm -rf ./mySimulation
rm -rf ./libManager.log*
rm -rf ./myAssemblerResults
#
#foreach file ( `find . | grep \\.test$` )
#rm -rf $file
#end
#
echo " Done."
echo " "
echo " Size in Kbytes after cleaning is: `du -sk`"
echo " "
#
