/** 3820656178 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef PLL_CP_INST_STATIC_H
#define PLL_CP_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_IPLY_25u_688	(*((double *) &instData [688]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_IPLY_25u_680	(*((double *) &instData [680]))	/* Branch Reln : Size = 8 bytes. */
#define _IPLY_25u_flow_664	(*((long *) &instData [664]))	/* Hidden Node : Size = 4 bytes. */
#define _V_Dynamic_CP_ITEST_25u_656	(*((double *) &instData [656]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_CP_ITEST_25u_648	(*((double *) &instData [648]))	/* Branch Reln : Size = 8 bytes. */
#define _CP_ITEST_25u_flow_632	(*((long *) &instData [632]))	/* Hidden Node : Size = 4 bytes. */
#define _I_Dynamic_OUT_624	(*((double *) &instData [624]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_OUT_616	(*((double *) &instData [616]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_PD_VSS_608	(*((double *) &instData [608]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_PD_VSS_600	(*((double *) &instData [600]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_DN_VSS_592	(*((double *) &instData [592]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_DN_VSS_584	(*((double *) &instData [584]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Dynamic_UP_VSS_576	(*((double *) &instData [576]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_UP_VSS_568	(*((double *) &instData [568]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_560	(*((double *) &instData [560]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_536	(*((double *) &instData [536]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_VDD_504	(*((double *) &instData [504]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_OUT_488	(*((double *) &instData [488]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_464	(*((double *) &instData [464]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_PD_VSS_448	(*((double *) &instData [448]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_432	(*((double *) &instData [432]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_DN_VSS_416	(*((double *) &instData [416]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_VDD_400	(*((double *) &instData [400]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_UP_VSS_384	(*((double *) &instData [384]))	/* Branch Load Group : Size = 8 bytes. */
#define _thr_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _VDD_value_304	(*((double *) &instData [304]))	/* VT_REAL : Size = 8 bytes. */
#define _VSS_value_264	(*((double *) &instData [264]))	/* VT_REAL : Size = 8 bytes. */
#define _IPLY_25u_voltage_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _CP_ITEST_25u_voltage_184	(*((double *) &instData [184]))	/* VT_REAL : Size = 8 bytes. */
#define _OUT_down_current_144	(*((double *) &instData [144]))	/* VT_REAL : Size = 8 bytes. */
#define _OUT_up_current_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _ttol_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _VSS_68	(*((long *) &instData [68]))	/* VT_NODE : Size = 4 bytes. */
#define _VDD_60	(*((long *) &instData [60]))	/* VT_NODE : Size = 4 bytes. */
#define _UP_52	(*((long *) &instData [52]))	/* VT_NODE : Size = 4 bytes. */
#define _PD_44	(*((long *) &instData [44]))	/* VT_NODE : Size = 4 bytes. */
#define _DN_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _IPLY_25u_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _OUT_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _CP_ITEST_25u_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* PLL_CP_INST_STATIC_H */
